### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by ThamerD** [UBC-MDS/DSCI522-2425-21-housing#10]
Our environment .yaml file contains many dependencies that we may or may not end up using in future milestones. After we finish the project, we should go back and remove all unused dependencies.

**Comment by gla32** [comment]
How would keeping the unused dependencies affect the project?

**Comment by ThamerD** [comment]
It makes our environment file unnecessarily large and downloads unneeded packages to your computer which will take time and space.

**Comment by ThamerD** [comment]
Done!
