### ISSUE TITLE
Runtime Error with Vegafusion 

### ISSUE THREAD

**Issue by gla32** [UBC-MDS/DSCI522-2425-21-housing#33]
![Screenshot 2024-11-29 at 12 15 04 AM](https://github.com/user-attachments/assets/1b9c9feb-fefe-4a2b-9888-09bc3c5e2344)

@ThamerD @yajing03 @tianjiao00

**Comment by ThamerD** [comment]
You can run:
`conda install vegafusion=1.6.9`

This is already mentioned in our environment file so you shouldn't have to do this unless you previously installed a different version of Vegafusion. Our Docker container doesn't have this issue
