### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by ThamerD** [UBC-MDS/DSCI522-2425-21-housing#73]
As per peer review guideline: 
**Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by yajing03** [comment]
More peer review suggestions:
Explicit instruction on fix render issues.
Need to add the Importance of the Research Question.
Need to add the limitations of the Ridge regression model or assumptions about the dataset.
