### ISSUE TITLE
change of file name.

### ISSUE THREAD

**Issue by tianjiao00** [UBC-MDS/DSCI522-2425-21-housing#85]
I have changed the scripts/predictions.py to scripts/predict.py to avoid duplicated name. 
Updated in README script part.

**Comment by yajing03** [comment]
Please avoid changing the file name, as some parts of the code rely on the original name. Renaming it will cause those references to break, preventing the code from running properly.

**Comment by tianjiao00** [comment]
Sure. I have change back the file names
