### ISSUE TITLE
Update readme with makefile instructions

### ISSUE THREAD

**Issue by ThamerD** [UBC-MDS/DSCI522-2425-21-housing#87]
We need to updated our steps to run the analysis using our new Makefile method

**Comment by yajing03** [comment]
So can we delete the script step? Since the makefile run all the scripts instead

**Comment by ThamerD** [comment]
Yes exactly. We can use this example: 
https://github.com/ttimbers/breast_cancer_predictor 

I will update the Docker parts tomorrow

**Comment by yajing03** [comment]
I'll update the instruction about makefile now
